// Vendors the exact Phosphor Icons used on the site into src/lib/icons.ts.
// Phosphor Icons are MIT-licensed (© Phosphor Icons). Run after adding a new
// icon name below:  node scripts/gen-icons.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = join(root, "node_modules", "@phosphor-icons", "core", "assets");

// --- The icons used across the site (bare names, no `ph-` prefix). ----------
const REGULAR = [
  "aperture", "apple-logo", "arrow-down-right", "arrow-left", "arrow-right",
  "arrow-up", "arrow-up-right", "arrows-left-right", "bank", "bezier-curve",
  "brain", "calendar-blank", "caret-down", "chart-line-up", "chat-text",
  "chats-circle", "check", "check-circle", "clock-countdown", "cookie",
  "copyright", "crosshair-simple", "currency-circle-dollar", "envelope-simple",
  "eye", "eye-slash", "fingerprint", "gear-six", "gift", "globe",
  "globe-hemisphere-west", "globe-simple", "google-play-logo", "handshake",
  "image-square", "info", "instagram-logo", "lifebuoy", "lightning",
  "link-simple", "list", "lock-simple", "magnifying-glass", "map-pin",
  "microphone-stage", "paper-plane-tilt", "pen-nib", "play", "plus", "power",
  "prohibit", "quotes", "receipt", "ruler", "scales", "scroll", "seal-check",
  "shield-check", "skull", "sparkle", "stack-simple", "student", "sun-dim",
  "trash-simple", "user", "user-circle", "warning", "warning-circle", "x",
  "x-circle",
];

// Icons also rendered in the `fill` weight (ph-fill).
const FILL = [
  "apple-logo", "google-play-logo", "check-circle", "lightning", "quotes",
];

const innerOf = (svg) =>
  svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .trim();

function load(weight, name) {
  const file =
    weight === "fill"
      ? join(ASSETS, "fill", `${name}-fill.svg`)
      : join(ASSETS, "regular", `${name}.svg`);
  if (!existsSync(file)) {
    throw new Error(`MISSING ${weight} icon: ${name} (${file})`);
  }
  return innerOf(readFileSync(file, "utf8"));
}

const regular = {};
const fill = {};
const missing = [];

for (const name of REGULAR) {
  try { regular[name] = load("regular", name); }
  catch (e) { missing.push(e.message); }
}
for (const name of FILL) {
  try { fill[name] = load("fill", name); }
  catch (e) { missing.push(e.message); }
}

if (missing.length) {
  console.error("\n".concat(missing.join("\n")));
  process.exit(1);
}

const entries = (obj) =>
  Object.keys(obj)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(obj[k])},`)
    .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Vendored Phosphor Icons (MIT, © Phosphor Icons). All paths render against
// \`fill="currentColor"\` on a 0 0 256 256 viewBox.
// To add/remove icons, edit scripts/gen-icons.mjs and rerun: node scripts/gen-icons.mjs

export const ICON_VIEWBOX = "0 0 256 256";

export const ICONS: Record<string, string> = {
${entries(regular)}
};

export const ICONS_FILL: Record<string, string> = {
${entries(fill)}
};

export type IconName = keyof typeof ICONS;
`;

writeFileSync(join(root, "src", "lib", "icons.ts"), out);
console.log(
  `Wrote src/lib/icons.ts — ${Object.keys(regular).length} regular, ${Object.keys(fill).length} fill icons.`,
);
